spring:
  application:
    name: CQRSQUERY
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    generate-ddl: true
    show-sql: true
    hibernate:
     ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    password: ${RABBITMQ_PASSWORD}
    username: ${RABBITMQ_USER}
  
axon:
  eventhandling:
    processors:
      amqpEvents:
        source: rabbitMQSpringAMQPMessageSource
        mode: subscribing
        
    